language: c
install:
    - sudo apt-get install libsoup2.4-dev
    - sudo apt-get install libjansson-dev
    - sudo apt-get install libglib2.0-dev
    - pkg-config --modversion jansson
script: "./configure && make && make check"

