language: c
install:
    - sudo apt-get install libsoup2.4-dev
    - sudo apt-get install libjansson-dev
    - sudo apt-get install libglib2.0-dev
    - sudo apt-get install gtk-doc-tools
script: "./configure && make && make check && make distcheck"

