#!/bin/bash

set -ex

aclocal --install -I m4 --force
if which gtkdocize >/dev/null 2>&1; then
    gtkdocize --copy
fi
autoconf
if which glibtoolize >/dev/null 2>&1; then
    glibtoolize --install --copy
else
    libtoolize --install --copy
fi
automake --add-missing --copy
./configure "$@"

